#!/bin/sh
SWTPMPATH=/opt/tcg/swTPM
mkdir -p $SWTPMPATH/tpmdata/$1
rm $SWTPMPATH/tpmdata/$1/00.permall
export TPM_SERVER_PORT=$1
export TPM_SERVER_NAME=127.0.0.1
export TPM_PORT=$1
export TPM_PATH=$SWTPMPATH/tpmdata/$1
$SWTPMPATH/tpm/tpm_server &>tpm.log &
sleep 1
$SWTPMPATH/libtpm/utils/tpminit
$SWTPMPATH/libtpm/utils/tpmbios
killall $SWTPMPATH/tpm/tpm_server
#sleep 1
$SWTPMPATH/tpm/tpm_server &>>tpm.log &
sleep 1
$SWTPMPATH/libtpm/utils/tpmbios
